name: Sudo
author: ErikX
api: 3.12.2
version: 1.0  #This is where you put the version of the plugin
main: ErikX\sudo\Main
# "ExampleName" will be a folder in the src folder and "Main" will be the file in the "ExampleName" folder
 
# Commands If ur plugin has commands do this:

commands:
  sudo:
    description: "Sudo a player!"
    permission: "sudo.use"

permissions:
  sudo.use:
    description: "Permission to sudo a player!"
    default: op
